/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
    mssp_sidebar: [
        {
            type: 'category',
            label: 'MSSP',
            collapsed: true,
            link: {
                type: 'doc',
                id: 'introduction'
            },
            items:[
                {
                    type: 'autogenerated',
                    dirName: '.'
                }
            ]
        }
    ]
};

module.exports = sidebars;